### ISSUE TITLE
IE浏览器纹理测试失败

### ISSUE THREAD

**Issue by paper520** [yelloxing/image3D#5]
- http://localhost:20000/test/core/texture-cube.html
- http://localhost:20000/test/core/texture-2d.html

操作系统：window10

浏览器：IE11

- 如何重现？

首先，命令行进入下面安装必要的node包：

```
npm install
```

然后启动测试服务器：

```
npm run server
```

最后，使用浏览器访问上面二个地址。

备注：别的浏览器目前测试都没有问题，并且用此浏览器测试别的用例都通过了。

**Comment by yelloxing** [comment]
使用没有问题，下面是运行截图：
![运行截图](https://user-images.githubusercontent.com/23074691/74125672-e3027c00-4c10-11ea-898b-d24e6cf88b94.PNG)

**Comment by yelloxing** [comment]
使用没有问题，下面是运行截图：

![运行截图](https://user-images.githubusercontent.com/23074691/74125951-a3885f80-4c11-11ea-9675-6326914794c0.PNG)

**Comment by yelloxing** [comment]
Tips:目前没有发现问题，先关闭，如果有发现问题者可以留言，我们会追踪的。
